In [1]:
age=20
if age>=18:
  print("Adult")

Adult

In [4]:
age=16
if age>=18:
  print("eligible")

else:
    print("not eligible")

not eligible

In [6]:
marks=72
if marks>=90:
  print("A+")
elif marks>=75:
    print("A")
elif marks>=60:
      print("B")
elif marks>=50:
      print("C")
else:
        print("fail")

B

In [8]:
age=25
fare = 80
if age>=18 and fare>=50:
  print("condition satisfied")

condition satisfied

In [9]:
age=25
survived=1
if age>=18:
  if survived ==1:
    print("adult survivor")

adult survivor

LISTS
ordered,indexed,mutable,can contasinduplicate values

In [10]:
my_list=[]
my_list

[]

In [40]:
ages=[22,38,36,35,35]
names=["ANUSHKA DWIVEDI","ANTRA YADAV","TASHU BHADAURIA"]
mixed=[10,"python",3.5,True]
print(names)

['ANUSHKA DWIVEDI', 'ANTRA YADAV', 'TASHU BHADAURIA']

In [38]:
print(ages)
print(names)
print(mixed)

[22, 38, 27, 35, 35]
['upman', 'yuvraaj', 'upman', 'yuvraaj', 'sachin', 'utkarsh', 'tanvi']
[10, 'python', 3.5, True]

In [19]:
print(ages[0])
print(ages[-1])
print(names[-1])
print(ages[1:4])
print(ages[:2])
print(ages[::2])

22
35
utkarsh
[38, 27, 35]
[22, 38]
[22, 27, 35]

In [18]:
print(ages)
ages[2]=27
print(ages)

[22, 38, 36, 35, 35]
[22, 38, 27, 35, 35]

In [20]:
print(names)
names.append("tanvi")
print(names)

['asha', 'sachin', 'utkarsh']
['asha', 'sachin', 'utkarsh', 'tanvi']

In [24]:
#insert
names.insert(1,"yuvraaj")
print(names)
names.insert(0,"upman")

['asha', 'yuvraaj', 'upman', 'yuvraaj', 'yuvraaj', 'sachin', 'utkarsh', 'tanvi']

In [25]:
#removing/deleting items
names.remove("asha")
print(names)

['upman', 'yuvraaj', 'upman', 'yuvraaj', 'yuvraaj', 'sachin', 'utkarsh', 'tanvi']

In [26]:
removed=names.pop(4)
print(removed)
print(names)

yuvraaj
['upman', 'yuvraaj', 'upman', 'yuvraaj', 'sachin', 'utkarsh', 'tanvi']

In [27]:
numbers=[40,10,30,20,10]
print(len(numbers))

5

In [29]:
print(numbers.count(10))

2

In [30]:
print(sum(numbers))

110

In [32]:
numbers.sort()
print(numbers)

[10, 10, 20, 30, 40]

In [33]:
numbers.reverse()
print(numbers)

[40, 30, 20, 10, 10]

In [34]:
students=[
    ["tanvi",21,"cse"],
    ["utkarsh",22,"cse"],
    ["upman",20,"cse"],
]

In [36]:
print(students[0])

['tanvi', 21, 'cse']

In [37]:
print(students[0][0])

tanvi

In [48]:
#combining lists with conditions
marks=[35,62,81,45,90]
for mark in marks:
  if mark>=50:
    print(mark,"pass")
  else:
      print(mark,"fail")

35 fail
62 pass
81 pass
45 fail
90 pass

make a dataframe

In [51]:
import pandas as pd
data={
    "customer":["a1","a2","a3","a4","a5"],
    "age":[22,35,28,40,55],
    "city":["delhi","mathura","lucknow","varanasi","agra"],
    "amount":[1200,3500,5400,2130,7000],
    "rating":[4,9,3,4,7]
}
df=pd.DataFrame(data)
print(df)

  customer  age      city  amount  rating
0       a1   22     delhi    1200       4
1       a2   35   mathura    3500       9
2       a3   28   lucknow    5400       3
3       a4   40  varanasi    2130       4
4       a5   55      agra    7000       7

In [52]:
df.loc[0:3,["customer","city","amount"]]

  customer      city  amount
0       a1     delhi    1200
1       a2   mathura    3500
2       a3   lucknow    5400
3       a4  varanasi    2130

In [54]:
#first 5 rows first 3 columns
df.iloc[0:5,0:3]

  customer  age      city
0       a1   22     delhi
1       a2   35   mathura
2       a3   28   lucknow
3       a4   40  varanasi
4       a5   55      agra